version: "3.9"
services:
  web:
    container_name: web
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    restart: always
volumes:
  postgres:
    driver: local
